[package]
name = "redox"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = { version = "0.23.1", default-features = false }

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_12"] }
lalrpop-util = { version = "0.23.1", default-features = false }
logos = "0.16.1"
