use crate::tokens::Token;
use crate::lexer::LexicalError;
use crate::ast;

grammar;

extern {
  type Location = usize;
  type Error = LexicalError;
  enum Token {
    "Create" => Token::Create,
    "Set" => Token::Set,
    "Display" => Token::Display,
    "with" => Token::With,
    "value" => Token::Value,
    "takes" => Token::Takes,
    "returns" => Token::Returns,
    "Copyof" => Token::Copyof,
    "to" => Token::To,
    "+" => Token::Add,
    "-" => Token::Subtract,
    "*" => Token::Multiply,
    "/" => Token::Divide,
    "%" => Token::Modulo,
    "=" => Token::Equals,
    "!=" => Token::NotEquals,
    "Append" => Token::Append,
    "Integer" => Token::Integer,
    "Real" => Token::Real,
    "Character" => Token::Character,
    "Text" => Token::Text,
    "Boolean" => Token::Boolean,
    "List" => Token::List,
    "Nothing" => Token::Nothing,
    "(" => Token::LeftParen,
    ")" => Token::RightParen,
    "[" => Token::LeftSquareBrace,
    "]" => Token::RightSquareBrace,
    "{" => Token::LeftBrace,
    "}" => Token::RightBrace,
    "," => Token::Comma,
    "<" => Token::LeftAngle,
    ">" => Token::RightAngle,
    "<=" => Token::LessEqual,
    ">=" => Token::GreaterEqual,
    "If" => Token::If,
    "then" => Token::Then,
    "otherwise" => Token::Otherwise,
    "While" => Token::While,
    "is" => Token::Is,
    "IntegerLiteral" => Token::IntegerLiteral(<i64>),
    "RealLiteral" => Token::RealLiteral(<f64>),
    "Identifier" => Token::Identifier(<String>),
    "TextLiteral" => Token::TextLiteral(<String>),
    "CharacterLiteral" => Token::CharacterLiteral(<char>),
    "BooleanLiteral" => Token::BooleanLiteral(<bool>),
  }
}

// ================================================================================================
// TODO: Add rest of AST grammar

pub Program: Vec<ast::Statement> = {
  <stmts:Statement*> => stmts
};

pub Statement: ast::Statement = {
  "Create" <var_type:FullType> <name:"Identifier"> => {
    ast::Statement::Create {
      identifier: name,
      var_type,
      value: Box::new(None),
    }
  },
  "Create" <var_type:FullType> <name:"Identifier"> "with" "value" <value:Expression> => {
    ast::Statement::Create {
      identifier: name,
      var_type,
      value: Box::new(Some(*value)),
    }
  },
  "Set" <name:"Identifier"> "to" <value:Expression> => {
    ast::Statement::Set {
      identifier: name,
      value
    }
  },
  "Display" <value:Expression> => {
    ast::Statement::Display { value }
  },
  "If" <cond:Expression> "{" <then:Statement*> "}" => {
    ast::Statement::If {
      condition: cond,
      then_contents: then,
      otherwise_contents: None,
    }
  },
  "If" <cond:Expression> "{" <then:Statement*> "}" "otherwise" "{" <otherwise:Statement*> "}" => {
    ast::Statement::If {
      condition: cond,
      then_contents: then,
      otherwise_contents: Some(otherwise),
    }
  },
  "While" <cond:Expression> "is" <proceed:"BooleanLiteral"> "{" <then:Statement*> "}" => {
    ast::Statement::While {
      condition: cond,
      proceed,
      then_contents: then,
    }
  },
  "While" <cond:Expression> "{" <then:Statement*> "}" => {
    ast::Statement::While {
      condition: cond,
      proceed: true,
      then_contents: then,
    }
  }
};

// TODO: Expressions
pub Expression: Box<ast::Expression> = {
  #[precedence(level="1")]
  Factor,
  #[precedence(level="3")] #[assoc(side="left")]
  <lhs:Expression> "[" <rhs:Expression> "]" => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Access,
      rhs
    })
  },
  #[precedence(level="3")] #[assoc(side="left")]
  <lhs:Expression> "*" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Mul,
      rhs
    })
  },
  <lhs:Expression> "/" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Div,
      rhs
    })
  },
  // In most languages, % has the same precedence as * and /
  <lhs:Expression> "%" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Modulo,
      rhs
    })
  },
  #[precedence(level="4")] #[assoc(side="left")]
  <lhs:Expression> "+" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Add,
      rhs
    })
  },
  <lhs:Expression> "-" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Sub,
      rhs
    })
  },
  // Equality and relative operators
  #[precedence(level="5")] #[assoc(side="left")]
  <lhs:Expression> "=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Equals,
      rhs
    })
  },
  <lhs:Expression> "!=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::NotEquals,
      rhs
    })
  },
  <lhs:Expression> "<" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LessThan,
      rhs
    })
  },
  <lhs:Expression> ">" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::GreaterThan,
      rhs
    })
  },
  <lhs:Expression> "<=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LessEqual,
      rhs
    })
  },
  <lhs:Expression> ">=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::GreaterEqual,
      rhs
    })
  },
};

pub Factor: Box<ast::Expression> = {
  #[precedence(level="1")]
  Term,
  #[precedence(level="2")]
  "-" <operand:Factor> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::Sub,
      operand
    })
  },
};

pub Term: Box<ast::Expression> = {
  <val:"IntegerLiteral"> => {
    Box::new(ast::Expression::IntegerLiteral(val))
  },
  <val:"RealLiteral"> => {
    Box::new(ast::Expression::RealLiteral(val))
  },
  <val:"TextLiteral"> => {
    Box::new(ast::Expression::TextLiteral(val))
  },
  <name:"Identifier"> => {
    Box::new(ast::Expression::Identifier(name))
  },
  ListLiteral,
  "(" <Expression> ")",
};

ListLiteral: Box<ast::Expression> = {
  "[" "]" => {
    Box::new(ast::Expression::ListLiteral { first: None, next: None })
  },
  "[" <items:ListItems> "]" => items,
};

ListItems: Box<ast::Expression> = {
  <first:Expression> => {
    Box::new(ast::Expression::ListLiteral { first: Some(first), next: None })
  },
  <first:Expression> "," <next:ListItems> => {
    Box::new(ast::Expression::ListLiteral { first: Some(first), next: Some(next) })
  },
};

pub FullType: ast::FullType = {
  <maintype:Type> => {
    ast::FullType {
      main: maintype,
      subtype: None
    }
  },
  <maintype:Type> "<" <subtype:FullType> ">" => {
    ast::FullType {
      main: maintype,
      subtype: Some(Box::new(subtype))
    }
  },
};

pub Type: ast::Type = {
    "Integer" => ast::Type::Integer,
    "Real" => ast::Type::Real,
    "Character" => ast::Type::Character,
    "Text" => ast::Type::Text,
    "Boolean" => ast::Type::Boolean,
    "List" => ast::Type::List,
    "Nothing" => ast::Type::Nothing,
};
