use crate::tokens::Token;
use crate::lexer::LexicalError;
use crate::ast;

grammar;

extern {
  type Location = usize;
  type Error = LexicalError;
  enum Token {
    "Create" => Token::Create,
    "Set" => Token::Set,
    "Display" => Token::Display,
    "with" => Token::With,
    "value" => Token::Value,
    "takes" => Token::Takes,
    "returns" => Token::Returns,
    "Copyof" => Token::Copyof,
    "to" => Token::To,
    "+" => Token::Add,
    "-" => Token::Subtract,
    "*" => Token::Multiply,
    "/" => Token::Divide,
    "%" => Token::Modulo,
    "=" => Token::Equals,
    "!=" => Token::NotEquals,
    "Append" => Token::Append,
    "Integer" => Token::Integer,
    "Real" => Token::Real,
    "Character" => Token::Character,
    "Text" => Token::Text,
    "Boolean" => Token::Boolean,
    "List" => Token::List,
    "Nothing" => Token::Nothing,
    "(" => Token::LeftParen,
    ")" => Token::RightParen,
    "[" => Token::LeftSquareBrace,
    "]" => Token::RightSquareBrace,
    "{" => Token::LeftBrace,
    "}" => Token::RightBrace,
    "," => Token::Comma,
    "<" => Token::LeftAngle,
    ">" => Token::RightAngle,
    "If" => Token::If,
    "then" => Token::Then,
    "otherwise" => Token::Otherwise,
    "While" => Token::While,
    "is" => Token::Is,
    "IntegerLiteral" => Token::IntegerLiteral(<i64>),
    "RealLiteral" => Token::RealLiteral(<f64>),
    "Identifier" => Token::Identifier(<String>),
    "TextLiteral" => Token::TextLiteral(<String>),
    "CharacterLiteral" => Token::CharacterLiteral(<char>),
    "BooleanLiteral" => Token::BooleanLiteral(<bool>)
  }
}

// ================================================================================================
// TODO: Add rest of AST grammar

pub Program: Vec<ast::Statement> = {
  <stmts:Statement*> => stmts
};

pub Statement: ast::Statement = {
  "Create" <var_type:Type> <name:"Identifier"> => {
    ast::Statement::Create {
      identifier: name,
      var_type,
      value: Box::new(None),
    }
  },
  "Create" <var_type:Type> <name:"Identifier"> "with" "value" <value:Expression> => {
    ast::Statement::Create {
      identifier: name,
      var_type,
      value: Box::new(Some(*value)),
    }
  },
  "Display" <value:Expression> => {
    ast::Statement::Display { value }
  },
  "If" <cond:Expression> "{" <then:Statement*> "}" => {
    ast::Statement::If {
      condition: cond,
      then_contents: then,
      otherwise_contents: None,
    }
  },
  "If" <cond:Expression> "{" <then:Statement*> "}" "otherwise" "{" <otherwise:Statement*> "}" => {
    ast::Statement::If {
      condition: cond,
      then_contents: then,
      otherwise_contents: Some(otherwise),
    }
  },
  "While" <cond:Expression> "is" <proceed:"BooleanLiteral"> "{" <then:Statement*> "}" => {
    ast::Statement::While {
      condition: cond,
      proceed,
      then_contents: then,
    }
  },
  "While" <cond:Expression> "{" <then:Statement*> "}" => {
    ast::Statement::While {
      condition: cond,
      proceed: true,
      then_contents: then,
    }
  }
};

// TODO: Expressions
pub Expression: Box<ast::Expression> = {
  #[precedence(level="1")]
  Term,
  #[precedence(level="2")] #[assoc(side="left")]
  <lhs:Expression> "*" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Mul,
      rhs
    })
  },
  <lhs:Expression> "/" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Div,
      rhs
    })
  },
  #[precedence(level="3")] #[assoc(side="left")]
  <lhs:Expression> "+" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Add,
      rhs
    })
  },
  <lhs:Expression> "-" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Sub,
      rhs
    })
  },
};

// TODO: Term
pub Term: Box<ast::Expression> = {
  <val:"IntegerLiteral"> => {
    Box::new(ast::Expression::IntegerLiteral(val))
  },
  <name:"Identifier"> => {
    Box::new(ast::Expression::Identifier(name))
  },
  "(" <Expression> ")",
};

pub Type: ast::Type = {
    "Integer" => ast::Type::Integer,
    "Real" => ast::Type::Real,
    "Character" => ast::Type::Character,
    "Text" => ast::Type::Text,
    "Boolean" => ast::Type::Boolean,
    "List" => ast::Type::List,
    "Nothing" => ast::Type::Nothing,
};
